import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <head>
          <link rel="icon" href="/icon.png" sizes="any" />
        </head>

        <body className={`antialiased`}>
          <NextTopLoader showSpinner={false} color="#006eb6" />
          {children}
        </body>
      </html>
      <ToastContainer />
    </>
  );
}
